### ISSUE TITLE
Documentation: creating Repo, Discussions, Project Wiki / 15h / $215

### ISSUE THREAD

**Issue by MouyouMoos** [MouyouMoos/myLife#4]
## Tasks
- [ ] creating the myLife Repository  (ETA 0.5h)
- [ ] come up with a decentralized and fair governance structure for the project (ETA 6h)
- [ ]  visualize the structure in a figma file (ETA 2h)
- [ ] create project Wiki which gives a project overview and explains the governance structure of the project which include the DAO, team, bounties and funding. (ETA 6h)
- [ ] creating Ideas and Problems Discussion (ETA 0.5h)

## Bounty-Price
$215 / ETA 15h

**Comment by MouyouMoos** [comment]
<img width="827" alt="daoStructure" src="https://github.com/MouyouMoos/myLife/assets/52453582/5195d28a-117f-474a-a22e-da7659313c81">
